# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="elkloriamod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0" #mandatory
 # A display name for the mod
displayName="Elkloria Mod" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
# credits="" #optional
# A text field displayed in the mod UI
authors="GameCraft910, a.k.a. Rishab Borah, author of the Elkloria series" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod is a mod intended to be based off of my book series, Elkloria.

The world of Elkloria itself is complex and expansive, and as such this mod will do its best to simulate it but will obviously not be able to fully capture it.

A list of hopeful features:
* All basic spells in Elkloria
* An enchantment system
* A spell combination/programming system matching the normal Elklorian spell programming system
* Magical abilities--wizard, dark wizard, witch/warlock, merpeople, psychomage
* Creatures from Elkloria
* Rituals, potions, and the like from Elkloria
* Complex and powerful Elklorian entities such as deities and the like
* Dimensions for the different universes in the story. Usifia and Vhestibulium might not be considered separate. It depends. Definitely will try to add a spirit realm, faery realm, demon realm, Alinusia, Typhon, etc.

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.elkloriamod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.elkloriamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
